In [2]:
import numpy as np

In [3]:
np.linalg.svd

<function numpy.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)>

In [4]:
A = np.array([[1 ,1 ,0.41],
             [-1,0,0.41],
             [0,1,-0.41]])

In [5]:
np.linalg.svd(A)

(array([[-8.16496581e-01, -1.88904597e-16, -5.77350269e-01],
        [ 4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
        [-4.08248290e-01, -7.07106781e-01,  5.77350269e-01]]),
 array([1.73205081, 1.        , 0.71014083]),
 array([[-7.07106781e-01, -7.07106781e-01,  5.55111512e-17],
        [ 7.07106781e-01, -7.07106781e-01,  5.55111512e-17],
        [-0.00000000e+00, -7.85046229e-17, -1.00000000e+00]]))

In [8]:
def low_rank_approx(SVD=None, A=None, r=1):
    """
    Computes an r-rank approximation of a matrix
    given the component u, s, and v of it's SVD
    Requires: numpy
    """
    if not SVD:
        SVD = np.linalg.svd(A, full_matrices=False)
    u, s, v = SVD
    Ar = np.zeros((len(u), len(v)))
    for i in range(r):
        Ar += s[i] * np.outer(u.T[i], v[i])
    return Ar

In [9]:
low_rank_approx(A=A)

array([[ 1.00000000e+00,  1.00000000e+00, -7.85046229e-17],
       [-5.00000000e-01, -5.00000000e-01,  3.92523115e-17],
       [ 5.00000000e-01,  5.00000000e-01, -3.92523115e-17]])

In [3]:
A = np.array([[1,1],
             [1,0],
             [1,1]])

In [4]:
u = np.array([[0.8880],
             [0.3251],
             [0.3251]])

In [6]:
P = np.identity(3)-2*u.dot(u.T)

In [7]:
P

array([[-0.577088  , -0.5773776 , -0.5773776 ],
       [-0.5773776 ,  0.78861998, -0.21138002],
       [-0.5773776 , -0.21138002,  0.78861998]])

In [15]:
P2 = np.array([[1  , 0 , 0 ],
       [0 ,  -0.259, -0.966],
       [0, -0.966,  0.2597]])

In [16]:
P.T.dot(P2.T)

array([[-5.77088000e-01,  7.07287560e-01,  4.07801799e-01],
       [-5.77377600e-01, -5.94755000e-05, -8.16702292e-01],
       [-5.77377600e-01, -7.07059475e-01,  4.08997708e-01]])

In [11]:
u2 = np.array([[0.02761],
             [0.2115]])

In [12]:
P2 = np.identity(2)-2*u2.dot(u2.T)

In [13]:
P2

array([[ 0.99847538, -0.01167903],
       [-0.01167903,  0.9105355 ]])

In [14]:
A2 = P2.dot(A1)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [22]:
R1 = np.array([[12/np.sqrt(180),6/np.sqrt(180),0],
              [-6/np.sqrt(180),12/np.sqrt(180),0],
                [0,0,1]])

In [23]:
A1 = R1.dot(A)

In [24]:
A1

array([[ 13.41640786,  29.06888371, -26.83281573],
       [  0.        , 172.17723427, -62.60990337],
       [ -4.        ,  24.        , -41.        ]])

In [25]:
R2 = np.array([[np.sqrt(180)/14,0,-2/7],
              [0,1,0],
                [2/7,0,np.sqrt(180)/14]])

In [26]:
A2 = R2.dot(A1)

In [27]:
A2

array([[ 14.        ,  21.        , -14.        ],
       [  0.        , 172.17723427, -62.60990337],
       [  0.        ,  31.30495168, -46.95742753]])

In [28]:
cos = 172.17723427 / (np.sqrt(31.30495168**2+172.17723427**2))
sin = -31.3049516 / (np.sqrt(31.30495168**2+172.17723427**2))


In [33]:
-sin

0.17888543771266888

In [29]:
R3 = np.array([[1,0,0],
              [0,cos,-sin],
                [0,sin,cos]])

In [30]:
A3 = R3.dot(A2)

In [31]:
A3

array([[ 1.40000000e+01,  2.10000000e+01, -1.40000000e+01],
       [ 0.00000000e+00,  1.75000000e+02, -7.00000000e+01],
       [ 0.00000000e+00,  8.40761582e-08, -3.50000000e+01]])

In [34]:
Q = R1.T.dot(R2.T).dot(R3.T)

In [35]:
Q

array([[ 0.85714286, -0.39428571,  0.33142857],
       [ 0.42857143,  0.90285714, -0.03428571],
       [-0.28571429,  0.17142857,  0.94285714]])

In [37]:
Aa = Q.dot(A3)

In [38]:
Aa

array([[ 12.        , -50.99999999,   4.        ],
       [  6.        , 166.99999997, -67.99999999],
       [ -4.        ,  24.        , -40.99999999]])

In [39]:
qq = Q

In [46]:
qq[0,2] = -qq[0,2]

In [47]:
qq

array([[ 0.85714286, -0.39428571, -0.33142857],
       [ 0.42857143,  0.90285714,  0.03428571],
       [-0.28571429,  0.17142857, -0.94285714]])

In [51]:
Rr = A3
Rr[2,2] = -Rr[2,2]

In [52]:
qq.dot(Rr)

array([[ 12.        , -51.00000004,   4.        ],
       [  6.        , 166.99999998, -67.99999999],
       [ -4.        ,  23.99999984, -40.99999999]])

In [17]:
R1 = np.array([[0.8944,-0.4472],
              [0.4472,0.8944]])

In [18]:
A = np.array([[4,1],
             [-2,-1]])

In [19]:
R1.dot(A)

array([[ 4.472 ,  1.3416],
       [ 0.    , -0.4472]])

In [21]:
np.identity(2)*2

array([[2., 0.],
       [0., 2.]])