In [1]:
import numpy as np
import numpy.linalg as npli
import scipy.io as sio
import scipy.sparse as sp
import scipy.sparse.linalg
import time

In [2]:
matrix = sio.mmread("p2p-Gnutella30.mtx")

In [3]:
matrix = sp.csr_matrix(matrix)

In [5]:
D = D(matrix)
A = sp.csr_matrix(matrix.dot(D))

In [8]:
eig, a = scipy.sparse.linalg.eigs(A, k=2, which='LR')

In [9]:
abs(eig[1])/abs(eig[0])

0.7370423311656258

In [10]:
eig[1]

(0.4916804933129786-0.03081023377250906j)

In [11]:
eig[0]

(0.6684078503924712+0j)

In [4]:
A = matrix.dot()

TypeError: dot() missing 1 required positional argument: 'other'

In [ ]:
m = 0.15
n = matrix.shape[0]
e = np.ones((1,n))
z = np.full((1,n),m/n)
z.shape

In [5]:
a = np.array([[0, 1, 7, 0],
              [0, 0, 2, 19]])
print(a.reshape(-1))

[ 0  1  7  0  0  0  2 19]


In [6]:
c = 1/a.sum(axis=0).reshape(-1)

<ipython-input-6-a0039928a334>:1: RuntimeWarning: divide by zero encountered in true_divide
  c = 1/a.sum(axis=0).reshape(-1)


In [7]:
c[ ~ np.isfinite(c)] = 0

In [8]:
c

array([0.        , 1.        , 0.11111111, 0.05263158])

In [9]:
matrix[:,1]

<36682x1 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [10]:
A[,:1]

SyntaxError: invalid syntax (<ipython-input-10-709e030f5c9b>, line 1)

In [11]:
np.shape(A)
np.shape(matrix)

NameError: name 'A' is not defined

In [12]:
zj = [m/n if A[:,i].count_nonzero()>0 else 1./n for i in range(n)]

NameError: name 'n' is not defined

In [13]:
zj

NameError: name 'zj' is not defined

In [14]:
A = sp.csr_matrix(matrix.dot(D))

NameError: name 'D' is not defined

In [4]:
def D(G):
    with np.errstate(divide='ignore', invalid='ignore'):
        d = np.divide(1.,np.asarray(G.sum(axis=0)).reshape(-1))
    #Remove NaN's and Inf's
    d[d == np.isfinite(d)] = 0
    #Construct a sparse matrix from diagonals.
    return sp.diags(d)

In [16]:
1e-4

0.0001

In [17]:
10e-4

0.001

In [18]:
xk_1=  np.ones((n,1))/n
xk_1

NameError: name 'n' is not defined

In [19]:
def PM_PR(A,m,tol):
    n = A.shape[0]
    tic = time.time()
    e = np.ones((n,1))
    zj = np.asarray([m/n if A[:,i].count_nonzero()>0 else 1./n for i in range(n)])
    
    xk = np.ones((n,1))
    xk1=  np.ones((n,1))/n
    
    while np.linalg.norm(xk1-xk) > tol:
        xk = xk1
        zxk = zj.dot(xk)
        xk1 = (1-m)*A.dot(xk)+e*zxk
    print("Execution time of the power method for PR:",time.time()-tic,"seconds")
    #Normalitzation
    xk1 = xk1/np.sum(xk1)
    return xk1
        
        
    

In [20]:
def diagonal(matrix):
    with np.errstate(divide='ignore', invalid='ignore'):
        d = np.divide(1.,np.asarray(matrix.sum(axis=0)).reshape(-1))
    #Remove NaN's and Inf's
    np.ma.masked_array(d, ~np.isfinite(d)).filled(0)
    #Construct a sparse matrix from diagonals.
    return sp.diags(d)

In [21]:
matrix = sio.mmread("p2p-Gnutella30.mtx")
matrix = sp.csr_matrix(matrix)
D = diagonal(matrix)
A = sp.csr_matrix(matrix.dot(D))
xk1 = PM_PR(A,0.15,10e-4)
print(xk1)

Execution time of the power method for PR: 20.65072250366211 seconds
[[1.36630683e-04]
 [4.42875728e-06]
 [6.53321166e-05]
 ...
 [4.42875728e-06]
 [4.42875728e-06]
 [4.42875728e-06]]


In [22]:
xk1

array([[1.36630683e-04],
       [4.42875728e-06],
       [6.53321166e-05],
       ...,
       [4.42875728e-06],
       [4.42875728e-06],
       [4.42875728e-06]])

In [23]:
10e-5

0.0001

In [24]:
float(1e-5)

1e-05

In [25]:
1e-5 == 10e-4

False

In [26]:
A1 = spsp.csr_matrix(np.asarray([ [0, 0, 0, 1./2], [1./3, 0, 0, 0], [1./3, 1./2, 0, 1./2], [1./3, 1./2, 0, 0] ]))

NameError: name 'spsp' is not defined

In [30]:
A1

NameError: name 'A1' is not defined

In [42]:
A1 = np.asarray([ [0, 0, 1, 1./2], [1./3, 0, 0, 0], [1./3, 1./2, 0, 1./2], [1./3, 1./2, 0, 0] ])
A1

array([[0.        , 0.        , 1.        , 0.5       ],
       [0.33333333, 0.        , 0.        , 0.        ],
       [0.33333333, 0.5       , 0.        , 0.5       ],
       [0.33333333, 0.5       , 0.        , 0.        ]])

In [43]:
print(A1.todense())
print(A1.shape)

AttributeError: 'numpy.ndarray' object has no attribute 'todense'

In [45]:
A1[0].todense()

AttributeError: 'numpy.ndarray' object has no attribute 'todense'

In [46]:
rows = A1.nonzero()[0]
columns = A1.nonzero()[1]

In [47]:
rows

array([0, 0, 1, 2, 2, 2, 3, 3], dtype=int64)

In [48]:
L = L_(rows,columns)

In [49]:
print(columns)
print(rows)

[2 3 0 0 1 3 0 1]
[0 0 1 2 2 2 3 3]


In [50]:
L

{2: array([0], dtype=int64),
 3: array([0, 2], dtype=int64),
 0: array([1, 2, 3], dtype=int64),
 1: array([2, 3], dtype=int64)}

In [51]:
def makeIndices(rows,cols):
	indices = {}
	for i in range(len(cols)):
		colIndex = columns[i]
		if colIndex in indices:
			indices[colIndex] = np.append(indices[colIndex],rows[i])
		else:
			indices[i] = np.array([rows[i]])
		return indices

In [52]:
#Create L
def L_(rows, columns):
    L={}
    for i in range(len(columns)):
        col = columns[i]
        if col in L:
            L[col] = np.append(L[col], rows[i])
        else:
            L[col] = np.asarray([rows[i]])
    return L

def c_(L, j):
    if j in L:
        return len(L[j])
    else:
        return 0
    
def PR_method_nomatrix(rows, columns, m, n, tol=1e-5):
    t0 = time.time()
    x = np.ones((n,1))/n
    xc = np.ones((n,1))
    L = makeIndices(rows, columns)
    while (npli.norm(x-xc, np.inf)>tol):
        xc =  x
        x = np.zeros((n,1))
        for j in range(n):
            print("J:",j)
            print("c: ",c_(L, j))
            if (c_(L, j)==0):
                x += xc[j]/n
            else:
                x[L[j]] += xc[j]/c_(L,j)
        x = (1.-m)*x + m/n
    print( "Time using power method without storing the matrices", time.time() - t0, 's')
    print( x/np.sum(x))

In [53]:
PR_method_nomatrix(rows,columns,0.15,A1.shape[0],1e-5)

J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0
J: 3
c:  0
J: 0
c:  1
J: 1
c:  0
J: 2
c:  0