In [1]:
import numpy as np


In [153]:
def ConjMethod(A,b,x0):
    for i in range(5000):
        r0 = residu(A,b,x0)
        alpha = getAlpha(A,r0)[0][0]
        x = point(r0,alpha,x0)
        r1 = newRes(A,r0,alpha)
        beta = getBeta(r0,r1)
        x0 = point2(r1,beta,r0)
    print(x,x0)

In [154]:
A = np.array([[1,0,0],[0,2,0],[0,0,3]])
b = np.array([[1],[1],[1]])
x0 = np.array([[1],[1],[1]])

ConjMethod(A,b,x0)

[[0.62345659]
 [0.42185256]
 [0.40543257]] [[ 0.39223479]
 [ 0.17317112]
 [-0.17678664]]


In [146]:
def residu(A,b,x0):
    return b-np.dot(A,x0)

In [152]:
def getAlpha(A,r0):
    nomi = np.dot(np.transpose(r0),r0)
    deno = np.transpose(r0).dot(A).dot(r0)
    return (nomi/deno)
    

In [148]:
def point(r,alpha,x0):
    return x0+(alpha * r)

In [149]:
def newRes(A,r,alpha):
    return r-alpha*A.dot(r)

In [150]:
def getBeta(r0,r1):
    nomi = np.dot(np.transpose(r1),r1)
    deno = np.transpose(r0).dot(A).dot(r0)
    return (nomi/deno)

In [151]:
def point2(r1,beta,r0):
    return r1+(beta*r0)

In [206]:
def conjgrad(A, b, x):
    """
    A function to solve [A]{x} = {b} linear equation system with the 
    conjugate gradient method.
    More at: http://en.wikipedia.org/wiki/Conjugate_gradient_method
    ========== Parameters ==========
    A : matrix 
        A real symmetric positive definite matrix.
    b : vector
        The right hand side (RHS) vector of the system.
    x : vector
        The starting guess for the solution.
    """  
    r = b - np.dot(A, x)
    print(r)
    p = r
    rsold = np.dot(np.transpose(r), r)
    
    for i in range(len(b)):
        print(i)
        Ap = np.dot(A, p)
        alpha = rsold / np.dot(np.transpose(p), Ap)
        print("SF",alpha)
        x = x + alpha[0][0]*p
        print(x)
        r = r - alpha[0][0]* Ap
        print("r",r)
        rsnew = np.dot(np.transpose(r), r)
        print("aa",rsnew/rsold)
        print(np.sqrt(rsnew))
        if np.sqrt(rsnew) < 1e-8:
            break
        p = r + (rsnew/rsold)*p
        print(p)
        
        rsold = rsnew
    return x

In [207]:
A = np.array([[1,0,0],[0,2,0],[0,0,3]])
b = np.array([[1],[1],[1]])
x0 = np.array([[1],[2],[1]])

conjgrad(A,b,x0)

[[ 0]
 [-3]
 [-2]]
0
SF [[0.43333333]]
[[1.        ]
 [0.7       ]
 [0.13333333]]
r [[ 0. ]
 [-0.4]
 [ 0.6]]
aa [[0.04]]
[[0.72111026]]
[[ 0.  ]
 [-0.52]
 [ 0.52]]
1
SF [[0.38461538]]
[[1.        ]
 [0.5       ]
 [0.33333333]]
r [[ 0.00000000e+00]
 [-5.55111512e-17]
 [ 0.00000000e+00]]
aa [[5.92593829e-33]]
[[5.55111512e-17]]


array([[1.        ],
       [0.5       ],
       [0.33333333]])

In [201]:
5.92593829e-33

5.92593829e-33

In [203]:
5.9259*10**-33

5.925900000000001e-33